name: Playwright Tests

on:
  pull_request:
    branches:
      - dev
      - main

jobs:
  test:
    name: üß™ ${{ matrix.project }} E2E Tests
    runs-on: ${{ matrix.os }}
    timeout-minutes: 20
    env:
      PLAYWRIGHT_BROWSERS_PATH: ${{ matrix.cache_dir }}
      PW_CI_REPORTER: dot
      PW_CI_WORKERS: ${{ matrix.workers }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - project: chromium
            os: ubuntu-latest
            cache_dir: /home/runner/.cache/ms-playwright
            workers: 3

          # - project: firefox
          #   os: ubuntu-latest
          #   cache_dir: ~/.cache/ms-playwright

          - project: webkit
            os: macos-14
            cache_dir: /Users/runner/Library/Caches/ms-playwright
            workers: 2
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "yarn"

      - name: Install dependencies
        env:
          PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
        run: yarn install --immutable

      - name: Write out playwright version
        run: yarn --silent playwright --version > .playwright-version

      - name: ‚ö°Ô∏è Cache playwright binaries
        uses: actions/cache@v4
        id: playwright-cache
        with:
          path: ${{ matrix.cache_dir }}
          key: ${{ runner.os }}-${{ matrix.project }}-pw-${{ hashFiles('**/.playwright-version') }}

      - name: Install Playwright Browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: yarn playwright install --with-deps ${{ matrix.project }}

      - name: Run Playwright tests
        run: yarn test --project=${{ matrix.project }}
